import { writeFileSync } from 'fs';
import { promisify } from 'util';
import * as child from 'child_process';
const exec = promisify(child.exec);

async function createVersionsFile(filename: string) {
  const revision = (await exec('git rev-parse --short HEAD')).stdout
    .toString()
    .trim();

  console.log(
    `version: '${process.env['npm_package_version']}', revision: '${revision}'`,
  );

  const content = `
// this file is automatically generated by git.version.ts script
export const versions = {
  version: '${process.env['npm_package_version']}',
  revision: '${revision}'
};`;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('versions.ts');
